### ISSUE TITLE
Logging Framework

### ISSUE THREAD

**Issue by NilsG-S** [TTUSDC/CPCEEDWebApp#19]
As mentioned by @asclines we might want to consider adding some kind of logging framework to the project.

Redux actually has a lot of synergy with debuggers/loggers, because it allows application state to be recorded.

**Comment by asclines** [comment]
[Tracer](https://github.com/baryon/tracer) is one I've used before and really like.

**Comment by NilsG-S** [comment]
[bunyan](https://github.com/trentm/node-bunyan) can be used for both server and browser. Each instance of bunyan can have its own logging levels.
[winston](https://github.com/winstonjs/winston) seems to have similar functionality.

**Comment by asclines** [comment]
+1 for Bunyan

**Comment by NilsG-S** [comment]
Should we care that bunyan's logging levels aren't standard (compliant with RFC 5424)?

**Comment by asclines** [comment]
I think not. Unless there is a good reason to

**Comment by asclines** [comment]
So to revisit this problem, it is to my understanding that as noted in PR #66 , webpack is somehow the complicating factor in logging. @NilsG-S Can you give more details?

**Comment by NilsG-S** [comment]
I should clarify that statement a little. All I know is that the combination of Webpack, Bunyan, and Mocha does not function.

Here is what I know:

- Bunyan can be used with Mocha. I made a test that could be run without Webpack and imported Bunyan. All of the tests passed and Bunyan produced output.
- Bunyan can be used with Webpack. The code currently up on the `logging` branch functions properly when you use `npm start`. The issues only appear when you try to run tests (Webpack + Bunyan + Mocha). Also the documentation for Bunyan includes a section on using it with Webpack.
  - This may not be relevant, but I noticed that the pid for Bunyan output on the web browser is `undefined`.
- The tests bundled with Webpack, Bunyan, and Mocha compile without errors. They fail as soon as the Mocha test runner encounters a Bunyan import. You don't even necessarily have to do anything with Bunyan, just import it.

Here is what I don't know:

- Which party is causing the problem.
- What an `unknown runtime environment` error means.

**Comment by asclines** [comment]
This wouldn't by chance be a es5 vs. es6 thing would it?

**Comment by NilsG-S** [comment]
I doubt it. I used Bunyan with both es5 and es6 syntax when I was trying without webpack. Although I was using babel in the configuration you used originally: `mocha --compilers js:babel-core/register`.

**Comment by asclines** [comment]
okay, tomorrow I will pull that branch and experiment as well.

**Comment by asclines** [comment]
@NilsG-S one big difference between `npm start` and `npm test` is that `npm start` uses `webpack-dev-server` and `npm test` uses `webpack`. Upon replacing `webpack` with `webpack-dev-server` in `npm test` the code compiled successfully. Do you think that might lead toward a solution?

**Comment by NilsG-S** [comment]
@asclines `npm test` always built the bundle successfully, the issue was when trying to run it with Mocha. You don't see errors when using `webpack-dev-server` because it never actually calls the second half of `webpack-dev-server --env=test && mocha build/test.bundle.js`.

I agree that we should consider other options. I'm looking into some stuff right now.

**Comment by NilsG-S** [comment]
I found a more elegant way of doing my Bunyan hack using [Webpack Transform Loader](https://github.com/webpack-contrib/transform-loader). Basically we would replace the standard logger import path with a fake logger during test builds.

I'm also looking into using Karma to run our tests in the browser. Since Bunyan ran just fine using `webpack-dev-server`, I'm inclined to believe the `unknown runtime environment` error might be alleviated by the fact that Karma causes the tests to run in the browser (thanks @asclines for the inspiration).

**Comment by asclines** [comment]
Okay, and just in case it isn't clear to anyone reading this, the `unknown runtime environment` error is _thrown_ by Bunyan, but we are not sure it is _caused_ by bunyan.

**Comment by NilsG-S** [comment]
Alright, so using Karma fixed the problem. When I looked at the Travis output it had two places where it stated how many tests were running, one with 0/30 and one with 17/30. But I counted the number of `SUCCESS` outputs and it added up to 30, so I'm not too worried.

**Comment by asclines** [comment]
@NilsG-S why is Firefox a requirement? and does that apply to Travis CI as well?

**Comment by NilsG-S** [comment]
@asclines Karma runs tests in a browser and Travis CI comes with Firefox, so it was the most obvious choice. I could probably set it up to run on other browsers, but it would require more work. There won't be any more changes to the way we add tests. You just need to make sure your tests are linked back to `test/index.js` through imports.

**Comment by NilsG-S** [comment]
I could also set up multiple configurations, with one for Travis and one for normal development.

**Comment by asclines** [comment]
@NilsG-S nah we dont need to worry about multiple configurations. As for the Firefox requirement and the linking tests to `test/index.js` could you add that instruction to the documentation in the PR you are working on?

**Comment by NilsG-S** [comment]
@asclines Where do you think would be best to put that documentation?

**Comment by asclines** [comment]
We should probably have a `Testing your changes` section under `Making changes` in the `CONTRIBUTING.md` file

**Comment by NilsG-S** [comment]
@asclines Thanks, it's done!
