### ISSUE TITLE
Using ReactFire to connect app to Firebase

### ISSUE THREAD

**Issue by asclines** [TTUSDC/CPCEEDWebApp#2]
So the wonderful people at Firebase have created [ReactFire](https://github.com/firebase/reactfire) that makes it really easy to connect Firebase to ReactJS Apps. 

Since it is developed and maintained by the Firebase team, I believe adding this to our components will be a good/safe idea. However we are a team and this needs to be a team decision.

So go ahead and checkout their [repo](https://github.com/firebase/reactfire) and let's discuss any possible concerns someone might have about using this.

**Comment by StephanieKeck** [comment]
As ReactFire currently has no support for ES6 (https://github.com/firebase/reactfire/issues/38) which Facebook recommends (https://facebook.github.io/react/docs/installation.html#enabling-es6-and-jsx), I suggest we look into using [rebase](https://github.com/tylermcginnis/re-base) instead.

**Comment by asclines** [comment]
After further research (see: "googling") I concur.
