### ISSUE TITLE
Activity Reports relation to students

### ISSUE THREAD

**Issue by asclines** [TTUSDC/CPCEEDWebApp#26]
Is an activity report mapped to one student or can a single activity report be mapped to multiple students. If it can be mapped to multiple students, what is the scenario where that happens?

**Comment by NilsG-S** [comment]
I think we decided that events were for multiple students while activities were individual.

**Comment by asclines** [comment]
Okay, that will make things a little tricky when it comes to out the database is structured but I think I have a way.

**Comment by asclines** [comment]
Update, this is now being handled in #29
