### ISSUE TITLE
Activity/Event points

### ISSUE THREAD

**Issue by asclines** [TTUSDC/CPCEEDWebApp#27]
So in our App Data documentation we give "Activity/Event" a key titled "points". Is there a time when an "Activity/Event" will get points that are not defined by the "AEPoints"? If not, would it be better to assign it a "type" instead of "points" where the type maps to an object in the "AEPoints" database reference?

**Comment by NilsG-S** [comment]
I was under the impression that aepoints defined the number of points that one had to get in each category in order to be qualified for scholarships. Events can be worth any number of points.

**Comment by asclines** [comment]
Doesn't the 'E' in AEPoints stand for events?

**Comment by asclines** [comment]
I guess the real question here is, what's the different between Activity and Event. I was under the impression that Activity was for when it was just one student for thinks like Mentor Meetings whereas events would have multiple students in attendance such as Workshops.

**Comment by NilsG-S** [comment]
That's pretty much my understanding of it.

**Comment by StephanieKeck** [comment]
I think multi-student activity reports could exist in theory (though our specifications don't call for any). My understanding is that the main difference between the two is that they are submitted/ approved via two different systems.

**Comment by NilsG-S** [comment]
That's a good point. Weren't we talking about allowing students to create activities and restricting event creation to coordinators?

**Comment by StephanieKeck** [comment]
Mentors can also create events, but only for students under them, if we're still implementing mentors.

**Comment by StephanieKeck** [comment]
This may not be the place for it, but this brings up another point. I've been thinking about whether we should maybe go with activity-based permissions (ex 'canCreateEvents') instead of (or in addition to) role-based permissions (ex 'Coordinator'). This system would be more flexible long term.

**Comment by NilsG-S** [comment]
@asclines 

Alright, so when Patty sent me the email outlining the categories, she stated that the numbers were the "minimum for scholarship consideration per category" and that "students must meet all category minimum requirements for consideration (15pts total)."

Now, I think my belief that events and activities could be worth multiple points was flawed. It just doesn't seem like there are enough points required for this to be the case. So really it would be possible to just assign a category/type to an event/activity as you said.

**Comment by NilsG-S** [comment]
@StephanieKeck 

I'm going to create an issue for mentors, because they're technically a part of our spec.

I would post that comment in issue #23

**Comment by asclines** [comment]
@NilsG-S okay, I will update the AppData and database tools to match the idea of the Activity/Event type, but I will refrain from removing the points until we are fully committed to that.

**Comment by asclines** [comment]
@StephanieKeck yes multi-student reports _could_ exists, but they _don't_ exist in the specs. The biggest issue I see with multi-user reports is when it comes to approval. If they are lumped under one report, its a approve-all or reject-all situation as far as I can tell. Please correct me if I am wrong on that point.

**Comment by NilsG-S** [comment]
@asclines I don't think it would be a bad thing to keep `aepoints` around. If we want to check for whether a student is qualified for scholarships, we would have to check against those values.

**Comment by asclines** [comment]
@NilsG-S What do you mean? Won't we be keeping the total points earned by the student in the user object?

**Comment by NilsG-S** [comment]
Yeah, but couldn't they theoretically get more points in one category than is required? Then they could get the 15 point total without meeting the minimum requirements for every category.

**Comment by asclines** [comment]
aha! I have discovered a flaw in my understanding of how the Activity & Even points worked. I thought the values were how much the events were worth. So each Activity and Event are worth one point each in their respective categories? That means that the user object will have to be updated to reflect that.

**Comment by NilsG-S** [comment]
That's my understanding of it at least. Did you see the quote from Patty I put up earlier? That's from the second email chain if you want to get more context.

**Comment by asclines** [comment]
@NilsG-S Yes I went back to read some of the email chain to clarify.

**Comment by asclines** [comment]
Closing because I'm pretty sure this is resolved.
