### ISSUE TITLE
Activity & Event Database Object Proposal

### ISSUE THREAD

**Issue by asclines** [TTUSDC/CPCEEDWebApp#29]
So there are two routes we can take:

## Option 1
first we combine them as one object as so:
`/aeobjects`
```JSON
{
  "approvalStatus" : false,
  "students" : [],
  "category" : "category-value",
  "time" : "data-time-in-utc",
  "location" : "somee-place",
  "title" : "some-title",
  "description" : "some-description",
  "contact" : "contact-info",
  "image" : "image-file"
}
```

## Option 2
or we split into two database references   
`/activities` 
```JSON
{
  "approvalStatus" : false,
  "student" : "student-uid",
  "category" : "category-value",
  "time" : "data-time-in-utc",
  "location" : "somee-place",
  "title" : "some-title",
  "description" : "some-description",
  "contact" : "contact-info"
}
```
Notes:
- `contact` can contain the information on the who ran the activity i.e. when a student meets with a teacher the teachers info will be placed here. 
- 'student`: Since an activity is tied to one student, this is just 1 value instead of a list
- I removed the image key as it doesn't make sense for activity.

 `/events`  
```JSON
{
  "students" : [],
  "category" : "category-value",
  "time" : "data-time-in-utc",
  "location" : "somee-place",
  "title" : "some-title",
  "description" : "some-description",
  "contact" : "contact-info",
  "image" : "image-file"
}
```
Notes:
- I removed the `approvalStatus` key as to my understanding events are only created by coordinators. If that is wrong, I can easily add that back.
- `students` is a list since the relation can be 1 to many

I personally think the second option is better as it allows more precise control over the two separately, but it might be more work. Thoughts before I go through with this?

## Update:
We are going with option 2.  
With this object, the student object will now have two lists, one for the UIDs of the Activities they took part in and one for the UIDs of the Events the took part in.

**Comment by NilsG-S** [comment]
I think the second option is better as well. It handles the way that only coordinator created events can be seen by everyone more elegantly. Also, we may need a third object for mentor created events.

I did have one question. How difficult would it be to get a history of events for a specific student with this system?

**Comment by asclines** [comment]
@NilsG-S 
In regards to the mentor created events:
Why do we need a separate object for that? What are the differences between a mentor-created and a admin-created event? The only thing I can think of is students who can see it. Is there anything else?  

As for the history of events:
Each student object will contain a list of UIDs for events and activities. It will probably end up being two separate lists since we are now going with Option 2.

**Comment by StephanieKeck** [comment]
Re: history, my thoughts on implementing this would be a history object under /user, where each entry would consist of a time stamp and metadata.

**Comment by asclines** [comment]
@StephanieKeck if we give the student object a list of the UIDs of the Activities/Events they partook in, we can get all other information about that Activity/Event from the `/activities` & `/events` database references.

**Comment by StephanieKeck** [comment]
@asclines Wouldn't we lose the time stamp information with that method though?

**Comment by asclines** [comment]
@StephanieKeck The Activities/Events will hold their own timestamps.

**Comment by StephanieKeck** [comment]
@asclines This works for activities, but not for events. The events time stamp is for when the event was created, which is not the same as when the user confirmed the event, though I concede the difference between the two would be small. Also there are other events I thought would be a good idea to store in history, such as the time a student account was created/ approved, and by whom, as well as the time at which an activity report was approved rather than just created.

**Comment by asclines** [comment]
@StephanieKeck yes for the timestamp of the object created, but one of the keys in the Event object is data-time which is not the timestamp of the object created but a field the student fills in.

**Comment by StephanieKeck** [comment]
@asclines Okay, but I assume then that that is the time the user claims to have attended the activity/event? I may be misunderstanding, but it doesn't make sense for the user to fill anything in in terms of time for events when the system can do it automatically, as we are still planning to have users confirm events through a confirmation code, correct? If you're referring to the time a user fills in for when they claim an activity took place, it doesn't make sense to me to track that in history, as I'm talking about tracking when an activity was submitted and then approved or rejected by a coordinator.

**Comment by asclines** [comment]
@StephanieKeck Let's hash out #30 first, I think this solution to this problem can be more easily solved once we are all on the same page about whats going on there.
