### ISSUE TITLE
Replacing Redux

### ISSUE THREAD

**Issue by NilsG-S** [TTUSDC/CPCEEDWebApp#54]
This application doesn't seem to be utilizing any features from Redux that couldn't be provided with simpler methods. So the additional complexity it introduces doesn't seem particularly justified. My proposal is that at some point in the future we change to using localStorage to store the user object and implement some functions to return user permissions depending on user role.

 That said, Redux is functioning perfectly well for now.

**Comment by asclines** [comment]
I believe Local Storage should suffice.

**Comment by asclines** [comment]
Looking back at this, can we safely assume redux is here to stay?

**Comment by NilsG-S** [comment]
Yup
