### ISSUE TITLE
'npm start' on Unix system

### ISSUE THREAD

**Issue by asclines** [TTUSDC/CPCEEDWebApp#60]
This issue is for solving the problem where `npm start` is not working.

## Doesn't work
| node Version 	| npm Version 	| Operating System      	|
|--------------	|-------------	|-----------------------	|
| 7.6.0        	| 4.1.2       	| Mac OS Sierra 10.12.3 	|
| 6.10.0       	| 3.10.0      	| Windows w/ Bash       	|
| 7.7.1        	| 4.1.2       	| Windows w/ Bash       	|
| 6.10.0       	| 3.10.10     	| Windows w/ Bash       	|
## Comment Template

Follow template:

OS:
`npm -v`:  
`node -v`:    
Stacktrace: 

## Resolution
It works just fine on a _real_ Ubuntu distro (aka _not_ the Linux subsystem on Windows)

**Comment by StephanieKeck** [comment]
OS: Mac OS Sierra 10.12.3
`npm -v`: `4.1.2`
`node -v`: `v7.6.0`
stack trace: 
```
ERROR in ./~/css-loader!./~/sass-loader?{"outputStyle":"compressed","includePaths":"/Users/stephaniekeck/Documents/Projects and Tutorials/Coding/Web/Websites:Projects/TTUSDC CPCEED/CPCEEDWebApp/node_modules"}!./src/styles/grommet.scss
Module build failed: 
@import 'grommet/scss/vanilla/index.scss';
^
      File to import not found or unreadable: grommet/scss/vanilla/index.scss.
Parent style sheet: stdin
      in /Users/stephaniekeck/Documents/Projects and Tutorials/Coding/Web/Websites:Projects/TTUSDC CPCEED/CPCEEDWebApp/src/styles/grommet.scss (line 1, column 1)
 @ ./src/styles/grommet.scss 4:14-134
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/index.js
```

**Comment by asclines** [comment]
OS: Windows 10 using Ubuntu Bash
`npm -v`  : 3.10.0  
`node -v` : v6.10..0
Stacktrace: 
```

ERROR in ./~/css-loader!./~/sass-loader?{"outputStyle":"compressed","includePaths":"/mnt/c/Codebase/Projects/EOCApp/Frontend/node_modules"}!./src/styles/grommet.scss
Module build failed: Error: EINVAL: invalid argument, uv_interface_addresses
    at Error (native)
    at Object.lib.networkInterfaces (/mnt/c/Codebase/Projects/EOCApp/Frontend/node_modules/macaddress/index.js:31:21)
    at Object.lib.one (/mnt/c/Codebase/Projects/EOCApp/Frontend/node_modules/macaddress/index.js:79:26)
    at Object.<anonymous> (/mnt/c/Codebase/Projects/EOCApp/Frontend/node_modules/uniqid/index.js:15:77)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
 @ ./src/styles/grommet.scss 4:14-130
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/index.js
```

**Comment by NilsG-S** [comment]
Ubuntu Bash:
`npm -v`: 4.1.2
`node -v`: 7.7.1

ERROR in ./~/css-loader!./~/sass-loader?{"outputStyle":"compressed","includePaths":"/mnt/c/Users/nilsg/Documents/Programming/CPCEED/CPCEEDWebApp/node_modules"}!./src/styles/grommet.scss
Module build failed: Error: EINVAL: invalid argument, uv_interface_addresses
    at Object.lib.networkInterfaces (/mnt/c/Users/nilsg/Documents/Programming/CPCEED/CPCEEDWebApp/node_modules/macaddress/index.js:31:21)
    at Object.lib.one (/mnt/c/Users/nilsg/Documents/Programming/CPCEED/CPCEEDWebApp/node_modules/macaddress/index.js:79:26)
    at Object.<anonymous> (/mnt/c/Users/nilsg/Documents/Programming/CPCEED/CPCEEDWebApp/node_modules/uniqid/index.js:15:77)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
 @ ./src/styles/grommet.scss 4:14-134
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/index.js

Ubuntu Bash:
`npm -v`: 3.10.10
`node -v`: 6.10.0

ERROR in ./~/css-loader!./~/sass-loader?{"outputStyle":"compressed","includePaths":"/mnt/c/Users/nilsg/Documents/Programming/CPCEED/CPCEEDWebApp/node_modules"}!./src/styles/grommet.scss
Module build failed: Error: EINVAL: invalid argument, uv_interface_addresses
    at Error (native)
    at Object.lib.networkInterfaces (/mnt/c/Users/nilsg/Documents/Programming/CPCEED/CPCEEDWebApp/node_modules/macaddress/index.js:31:21)
    at Object.lib.one (/mnt/c/Users/nilsg/Documents/Programming/CPCEED/CPCEEDWebApp/node_modules/macaddress/index.js:79:26)
    at Object.<anonymous> (/mnt/c/Users/nilsg/Documents/Programming/CPCEED/CPCEEDWebApp/node_modules/uniqid/index.js:15:77)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
 @ ./src/styles/grommet.scss 4:14-134
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/index.js

Windows:
`npm -v`: 3.10.6
`node -v`: 6.5.0

No problems.

**Comment by NilsG-S** [comment]
Removing `import 'styles/grommet.scss';` makes the error go away, so it's probably an issue with the configuration with respect to sass-loader.

**Comment by NilsG-S** [comment]
Updating all loaders hasn't solved the problem

**Comment by NilsG-S** [comment]
@asclines @StephanieKeck 
The issue is not with any of my recent changes, I reverted to an older version and attempted to run `npm start` on my Ubuntu subsystem. Here is the error I got:

```
ERROR in EINVAL: invalid argument, uv_interface_addresses
 @ ./src/styles/grommet.scss 4:14-143
```

This is essentially the same message, just less verbose (which could be attributed to it being an older version of webpack). At any rate, this seems to be an issue with either the sass-loader configuration, the way that the style is being imported in `src\styles\grommet.scss`, or both.

@StephanieKeck 
It is unlikely that I will get this issue fixed in the next week, so if you want to do development I would advise that you get your Windows environment setup.

**Comment by NilsG-S** [comment]
I got everything setup on a virtual machine running Ubuntu Server 16.04 and I don't get any errors from running `npm start`. I'm not entirely surprised that Ubuntu Bash on Windows has issues, but I'm kinda surprised that @StephanieKeck is having problems. @asclines would you be able to replicate my result?

`npm -v`: 3.10.10
`node -v`: v6.10.0

**Comment by asclines** [comment]
@NilsG-S before I try to replicate your results, was that with what is currently on `master` or after you reverted things?

**Comment by NilsG-S** [comment]
@asclines I used what is currently on master

**Comment by asclines** [comment]
@NilsG-S My setup: 
- OS: ubuntu-16.04.2-server-amd64
- `node -v` : v7.7.1
- `npm -v` : 4.1.2 
- using the latest commit from `master`

Results:  
I was able to get webpack to compile successfully but the website was not loading.  I got a `refused to connect` message.

**Comment by NilsG-S** [comment]
@asclines I got everything setup on a laptop running Ubuntu and I was able to view the website.

- OS: ubuntu-16.04.1-desktop-amd64
- `node -v` : v6.10.0
- `npm -v` : 3.10.10 
- Using the latest commit from `master`

**Comment by asclines** [comment]
Got it to work following https://github.com/webpack/webpack-dev-server/issues/147

**Comment by NilsG-S** [comment]
@StephanieKeck Aside from Ubuntu Bash on Windows (which is highly suspect), yours is the only system that experiences this issue. Unless @mariots can replicate the problem on his Mac, this is likely to be a problem with your setup.

**Comment by asclines** [comment]
Closing as all issues that have been replicated have been resolved. If it turns out this issue is replicated on @mariots's mac we will open a new issue as that will be a different problem.

**Comment by mariots** [comment]
@channel I was able to run it on my mac with no errors. I did have to change the port because I already had a program running at the default port of 8000.

**Comment by asclines** [comment]
@mariots thanks!
